function d20compactedchargestatus = importStatus(filename, dataLines)
%IMPORTFILE Import data from a text file
%  D20COMPACTEDCHARGESTATUS = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  D20COMPACTEDCHARGESTATUS = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  d20compactedchargestatus = importfile("/Users/mikesimard/Desktop/Workspace/Data/Zeus/3d_20_compacted_charge_status.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Mar-2021 12:01:02

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["rosbagTimestamp", "header", "seq", "stamp", "secs", "nsecs", "frame_id", "Temperature", "OutputCurrent", "BusVoltage", "ClosedLoopError"];
opts.VariableTypes = ["double", "string", "double", "string", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["header", "stamp"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["header", "stamp"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "frame_id", "TrimNonNumeric", true);
opts = setvaropts(opts, "frame_id", "ThousandsSeparator", ",");

% Import the data
d20compactedchargestatus = readtable(filename, opts);

end