function d20compactedchargemotorpercent = importMotorPercent(filename, dataLines)
%IMPORTFILE Import data from a text file
%  D20COMPACTEDCHARGEMOTORPERCENT = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  D20COMPACTEDCHARGEMOTORPERCENT = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  d20compactedchargemotorpercent = importfile("/Users/mikesimard/Desktop/Workspace/Data/Zeus/3d_20_compacted_charge_motor_percent.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Mar-2021 12:00:40

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["rosbagTimestamp", "data"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
d20compactedchargemotorpercent = readtable(filename, opts);

end