function CIMMotorCurve12v = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CIMMOTORCURVE12V = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  CIMMOTORCURVE12V = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  CIMMotorCurve12v = importfile("/Users/mikesimard/OneDrive - USherbrooke/Sessions/Projet majeur de conception/Technique/Analyses/CIM-MotorCurve-12v.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Nov-2020 18:11:43

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["SpeedRPM", "TorqueNm", "CurrentA", "SuppliedPowerW", "OutputPowerW", "Efficiency", "PowerDissipationW"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
CIMMotorCurve12v = readtable(filename, opts);

end